version: "3"


services:
  redis:
    image: redis:alpine
    command: sh -c 'exec redis-server --requirepass $$REDIS_PASSWORD --save 300 1 --dir /data/ --dbfilename dump.rdb'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis-data:/data
    networks:
      - centry

  postgres:
    image: postgres:16.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_INITDB_ARGS=$POSTGRES_INITDB_ARGS
      - PGDATA=/data/pgdata
    volumes:
      - postgres-data:/data
    networks:
      - centry

  pylon_auth:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - APP_HOST=$APP_HOST
      - APP_PROTO=$APP_PROTO
      - DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
      - APPLICATION_SECRET_KEY=$APPLICATION_AUTH_SECRET_KEY
    volumes:
      - ./pylon_auth:/data
    depends_on:
      - redis
      - postgres
    networks:
      - centry

  pylon_main:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - APP_HOST=$APP_HOST
      - APP_PROTO=$APP_PROTO
      - SECRETS_MASTER_KEY=$SECRETS_MASTER_KEY
      - APPLICATION_SECRET_KEY=$APPLICATION_MAIN_SECRET_KEY
    volumes:
      - ./pylon_main:/data
    depends_on:
      - redis
      - postgres
      - pylon_auth
    networks:
      - centry

  pylon_indexer:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - ./pylon_indexer:/data
    depends_on:
      - redis
    networks:
      - centry


volumes:
  redis-data:
  postgres-data:


networks:
  centry:
