version: "3"

services:
  redis:
    image: redis:alpine
    command: sh -c 'exec redis-server --requirepass $$REDIS_PASSWORD --save 300 1 --dir /data/ --dbfilename dump.rdb'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    volumes:
      - redis-data:/data
    networks:
      - centry

  postgres:
    image: postgres:16.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - PGDATA=/data/pgdata
    volumes:
      - postgres-data:/data
    networks:
      - centry

  pylon_auth:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
    volumes:
      - ./pylon_auth:/data
      - ./ssl:/ssl
    depends_on:
      - redis
      - postgres
    networks:
      - centry

  pylon_main:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
    volumes:
      - ./pylon_main:/data
      - ./ssl:/ssl
    ports:
      - 80:8080
    depends_on:
      - redis
      - postgres
    networks:
      - centry

  pylon_indexer:
    image: getcarrier/pylon:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - PYLON_WEB_RUNTIME=gevent
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
    volumes:
      - ./pylon_indexer:/data
      - ./ssl:/ssl
    depends_on:
      - redis
    networks:
      - centry

  interceptor_main:
    image: getcarrier/interceptor:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - SUPERVISOR_CONF_PATH=/tmp/interceptor.conf
      - CPU_CORES=5
      - QUEUE_NAME=default
      - RAM_QUOTA=4g
      - CPU_QUOTA=1
      - ARBITER_RUNTIME=redis
      - REDIS_HOST=redis
      # - SSL_CERTS=/ssl/ca.crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/ssl
    depends_on:
      - redis
      - pylon_main
    networks:
      - centry

  interceptor_internal:
    image: getcarrier/interceptor:tasknode
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./envs/default.env
      - ./envs/override.env
    environment:
      - SUPERVISOR_CONF_PATH=/tmp/interceptor.conf
      - CPU_CORES=15
      - QUEUE_NAME=__internal
      - RAM_QUOTA=4g
      - CPU_QUOTA=1
      - ARBITER_RUNTIME=redis
      - REDIS_HOST=redis
      # - SSL_CERTS=/ssl/ca.crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/ssl
    depends_on:
      - redis
    networks:
      - centry

volumes:
  redis-data:
  postgres-data:

networks:
  centry:
