event_node:
  type: RedisEventNode
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  event_queue: ${NAME_PREFIX}_indexer
  hmac_key: ${INDEXER_HMAC_KEY}
  hmac_digest: sha512
  callback_workers: 16
  mute_first_failed_connections: 10
  use_ssl: ${REDIS_SSL}
  log_errors: true

nltk_data: /data/cache/nltk
api_url: http://pylon_main:8080

datasource_icon_path: /data/static/datasource_icon_path

disable_vectorstore_access: false
project_schemas: false
dataset_schemas: true
use_jsonb: true
