event_node:
  type: RedisEventNode
  host: redis
  port: 6379
  password: $REDIS_PASSWORD
  event_queue: indexer
  hmac_key: $HMAC_INDEXER_KEY
  hmac_digest: sha512
  callback_workers: 16
  mute_first_failed_connections: 10
  use_ssl: false
  log_errors: true

nltk_data: /data/cache/nltk
api_url: http://pylon_main:8080

datasource_icon_path: /data/static/datasource_icon_path
