alita_ui_url: "${APP_PROTO}://${APP_HOST}/alita_ui"

auto_setup: true
ai_project_allowed_domains: "centry.user"
add_admin_roles: ["system", "admin", "editor", "viewer", "prompt_lib_public", "prompt_lib_moderators", "public_admin"]
