settings:
  app_ip: ${APP_HOST}
  app_host: ${APP_PROTO}://${APP_HOST}
  app_scheme: ${APP_PROTO}
  #
  allow_cors: true
  #
  arbiter_runtime: redis
  redis_host: ${REDIS_HOST}
  redis_port: ${REDIS_PORT}
  redis_password: ${REDIS_PASSWORD}
  redis_use_ssl: ${REDIS_SSL}
  #
  force_inject_db: true
  #
  database_vendor: postgres
  database_engine_options:
    pool_pre_ping: true
    pool_size: 100
    max_overflow: 200
  postgres_host: ${POSTGRES_HOST}
  postgres_port: ${POSTGRES_PORT}
  postgres_user: ${POSTGRES_USER}
  postgres_password: ${POSTGRES_PASSWORD}
  postgres_db: ${POSTGRES_DB}
  #
  secrets_engine: database
  secrets_master_key: ${SECRETS_MASTER_KEY}
  #
  storage_engine: libcloud
  storage_libcloud_driver: LOCAL
  storage_libcloud_params:
    kwargs:
      key: /data/libcloud/storage
  storage_libcloud_encoder: base64


apply_shared_metadata: true
apply_project_metadata: true
