settings:
  app_ip: $APP_HOST
  app_host: $APP_PROTO://$APP_HOST
  app_scheme: $APP_PROTO
  arbiter_runtime: redis
  redis_host: redis
  redis_password: $REDIS_PASSWORD
  database_vendor: postgres
  postgres_host: postgres
  postgres_user: $POSTGRES_USER
  postgres_password: $POSTGRES_PASSWORD
  postgres_db: $POSTGRES_DB
  secrets_engine: database
  secrets_master_key: $SECRETS_MASTER_KEY
  storage_engine: libcloud
  storage_libcloud_driver: LOCAL
  storage_libcloud_params:
    kwargs:
      key: /data/storage
  storage_libcloud_encoder: base64
