nltk_data: /data/cache/nltk
tasknode_tmp: /data/cache/tasknode

# agent_memory_config:
#   type: postgres
#   connection_string: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/agentstate
#   connection_kwargs:
#     autocommit: true
