event_node:
  type: RedisEventNode
  host: redis
  port: 6379
  password: $REDIS_PASSWORD
  event_queue: indexer
  hmac_key: $HMAC_INDEXER_KEY
  hmac_digest: sha512
  callback_workers: 16
  mute_first_failed_connections: 10
  use_ssl: false
  log_errors: true

task_queue_debug: true
preloaded_models_enabled: false
preloaded_models: []
external_models_enabled: false
indexer_tasks_enabled: true
