url_prefix: "/oidc"

url_mode: external  # request, default
logout_mode: post  # get, local

client_id: ""
client_secret: ""

metadata_endpoint: ""
authorization_endpoint: ""
token_endpoint: ""
userinfo_endpoint: ""
end_session_endpoint: ""

metadata_endpoint_verify: false
token_endpoint_verify: false
userinfo_endpoint_verify: false
