APP_HOST=${APP_HOST}
APP_PROTO=http

COOKIES_SECURE=false

ALITA_RELEASE=${ALITA_RELEASE}

%{ if ALITA_REMOTE_REPO == 1}
LICENSE_USERNAME=${LIC_USERNAME}
LICENSE_PASSWORD=${LIC_PASSWORD}
%{else}
LICENSE_TOKEN=${LICENSE_TOKEN}
%{ endif }

DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}

NAME_PREFIX=centry

APPLICATION_AUTH_SECRET_KEY=${APP_AUTH_SECRET}
APPLICATION_MAIN_SECRET_KEY=${APP_MAIN_SECRET}

EVENT_HMAC_KEY=${EVENT_HMAC_KEY}
RPC_HMAC_KEY=${RPC_HMAC_KEY}
EXPOSURE_HMAC_KEY=${EXPOSURE_HMAC_KEY}
INDEXER_HMAC_KEY=${INDEXER_HMAC_KEY}

# changeme
SECRETS_MASTER_KEY=${MASTER_KEY}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_SSL=false
REDIS_PASSWORD=${REDIS_PASSWORD}

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=centry
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=db
POSTGRES_INITDB_ARGS=--data-checksums
